### ISSUE TITLE
Desk.insights_meta produces a 404

### ISSUE THREAD

**Issue by cshimvin** [chriswarren/desk#65]
Using Desk.insights_meta produces a 404:

<code>
C:/Ruby200-x64/lib/ruby/2.0.0/json/common.rb:155:in `parse': 757: unexpected token at '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> (Faraday::ParsingError)
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Page Not Found</title>
                <script type="text/javascript">
                        var headID = document.getElementsByTagName("head")[0];
                        var newScript = document.createElement('script');
                        newScript.type = 'text/javascript';
                        newScript.src = '//webassets.desk.com/assets/js/analytics/deskanalytics.js';
                        headID.appendChild(newScript);
                </script>

```
            <style>
                    body {
                            background: #f3f3f3;
                            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                            margin: 0;
                            padding: 0;
                    }
                    #container { position: absolute; width: 100%; height: 100%; }
                    #page { position: relative; width: 100%; height: 100%; }
                    #box {
                            background: #FFF;
                            border: 1px solid #CDCDCD;
                            width: 700px;
                            height: 300px;
                            position: absolute;
                            text-align: center;
                            top: 50%;
                            left: 50%;
                            margin: -200px 0 0 -350px;
                            -moz-border-radius: 5px;
                            -webkit-border-radius: 5px;
                    }
                    #box h1 {
                            font-size: 37px;
                            margin: 65px 0 0;
                    }
                    #box p {
                            color: #888;
                            font-size: 19px;
                            margin: 0;
                    }
                    #box a {
                            background: url("http://webassets.desk.com/new/images/buttons/homepage.png") 0 0 no-repeat;
                            display: block;
                            margin: 50px auto 0;
                            width: 184px;
                            height: 39px;
                            text-indent: -9000px;
                            overflow: hidden;
                    }
                    #box a:hover {
                            background-position: 0 -39px;
                    }
            </style>
    </head>
    <body>
            <div id="container">
                    <div id="page">
                            <div id="box">
                                    <h1>Sorry, we couldn't find that page.</h1>
                                    <p>Maybe it was moved, deleted, or you accidentally mistyped the URL.</p>
                                    <a href="/">Go to Homepage</a>
                            </div>
                    </div>
            </div>
    </body>
```

</html>
'
        from C:/Ruby200-x64/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response/parse_json.rb:11:in`block in class:ParseJson'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:48:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:48:in`parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:32:in`block in call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday_middleware-0.9.2/lib/faraday_middleware/response_middleware.rb:30:in`call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in`call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/multipart.rb:14:in`call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/desk-1.0.8/lib/faraday/request/multipart_with_file.rb:16:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in`build_response'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in`get'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/desk-1.0.8/lib/desk/request.rb:51:in `request'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/desk-1.0.8/lib/desk/request.rb:18:in`method_missing'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/desk-1.0.8/lib/desk/client/insight.rb:6:in `show_insights_meta'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/desk-1.0.8/lib/desk.rb:25:in`method_missing'
        from C:/xampp/htdocs/desk/cases.rb:84:in `show_insights'
</code>

https://gist.github.com/cshimvin/85b5a7a86d2c85fb3752fba736c75607

**Comment by chriswarren** [comment]
Thanks for reporting this. Would you be able to take a pass at fixing it and submitting a pull request?

**Comment by Cb-James** [comment]
#67 submitted. Just needed a URL update.
